Repository cloud-native-toolkit/terraform-util-clis, pull requests merged in 2022-02, with the labels that each got.

#11 Created script to install rosa cli
  .gitignore
  scripts/setup-binaries.sh
  scripts/setup-rosa.sh
  test/stages/stage2-clis.tf
  test/stages/variables.tf
Labels: enhancement, minor

#13 Adds support for github and gitlab clis
  .github/scripts/validate-deploy.sh
  scripts/setup-binaries.sh
  scripts/setup-gh.sh
  scripts/setup-glab.sh
  test/stages/stage2-clis.tf
  variables.tf
Labels: enhancement, minor

#15 Fix rosa-cli issues
  .github/scripts/validate-deploy.sh
  main.tf
  scripts/setup-binary-from-tgz.sh
  scripts/setup-rosa.sh
  test/stages/stage2-clis.tf
Labels: bug, patch

#16 Adds kubeseal to the list of downloadable clis
  .github/scripts/validate-deploy.sh
  README.md
  scripts/setup-binaries.sh
  scripts/setup-kubeseal.sh
  test/stages/stage2-clis.tf
  variables.tf
Labels: enhancement, minor

#17 Updates metadata workflows
  .github/workflows/publish-assets.yaml
  .github/workflows/verify.yaml
  version.tf
Labels: patch, chore
